# Generated by Django 2.2.12 on 2020-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200501_1327'),
        ('users', '0002_auto_20200430_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nnbn',
            field=models.ManyToManyField(blank=True, related_name='user_nnbn', to='home.HomePage'),
        ),
    ]
