# Generated by Django 2.2.12 on 2020-04-30 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='abc',
            field=models.ManyToManyField(blank=True, related_name='homepage_abc', to=settings.AUTH_USER_MODEL),
        ),
    ]
