# Generated by Django 2.2.12 on 2020-05-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_gfgf"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="abc",),
    ]
