# Generated by Django 2.2.12 on 2020-05-01 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_remove_homepage_abc"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="abc",
            field=models.ManyToManyField(
                blank=True, related_name="homepage_abc", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
